const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const HeaderSchema = new Schema({
  headerTitle: { type: String },
  headerTitle_en: { type: String },

  headerText: { type: String },
  headerText_en: { type: String },
  headerTextDropdown: { type: String },
  headerTextDropdown_en: { type: String },
  headerTextDropdown1: { type: String },
  headerTextDropdown1_en: { type: String },
  headerTextDropdown2: { type: String },
  headerTextDropdown2_en: { type: String },
  headerTextDropdown3: { type: String },
  headerTextDropdown3_en: { type: String },

  headerText1: { type: String },
  headerText1_en: { type: String },
  headerText1Dropdown: { type: String },
  headerText1Dropdown_en: { type: String },
  headerText1Dropdown1: { type: String },
  headerText1Dropdown1_en: { type: String },
  headerText1Dropdown2: { type: String },
  headerText1Dropdown2_en: { type: String },
  headerText1Dropdown3: { type: String },
  headerText1Dropdown3_en: { type: String },

  headerText2: { type: String },
  headerText2_en: { type: String },
  headerText2Dropdown: { type: String },
  headerText2Dropdown_en: { type: String },
  headerText2Dropdown1: { type: String },
  headerText2Dropdown1_en: { type: String },
  headerText2Dropdown2: { type: String },
  headerText2Dropdown2_en: { type: String },
  headerText2Dropdown3: { type: String },
  headerText2Dropdown3_en: { type: String },

  headerText3: { type: String },
  headerText3_en: { type: String },
  headerText3Dropdown: { type: String },
  headerText3Dropdown_en: { type: String },
  headerText3Dropdown1: { type: String },
  headerText3Dropdown1_en: { type: String },
  headerText3Dropdown2: { type: String },
  headerText3Dropdown2_en: { type: String },
  headerText3Dropdown3: { type: String },
  headerText3Dropdown3_en: { type: String },

  headerText4: { type: String },
  headerText4_en: { type: String },
  headerText4Dropdown: { type: String },
  headerText4Dropdown_en: { type: String },
  headerText4Dropdown1: { type: String },
  headerText4Dropdown1_en: { type: String },
  headerText4Dropdown2: { type: String },
  headerText4Dropdown2_en: { type: String },
  headerText4Dropdown3: { type: String },
  headerText4Dropdown3_en: { type: String },

  headerText5: { type: String },
  headerText5_en: { type: String },
  headerText5Dropdown: { type: String },
  headerText5Dropdown_en: { type: String },
  headerText5Dropdown1: { type: String },
  headerText5Dropdown1_en: { type: String },
  headerText5Dropdown2: { type: String },
  headerText5Dropdown2_en: { type: String },
  headerText5Dropdown3: { type: String },
  headerText5Dropdown3_en: { type: String },
});

module.exports = mongoose.model("Header", HeaderSchema);
