import "./globals.css";
import { Header, Footer } from "@/components";

export const metadata = {
  title: "Otel Marmaris",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <main className="py-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
